=== DanielleAlloy/XML-capstone-project/combinedSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
    Macintosh Laptop and Desktop Computers Comparison
	  BCS 303 - Midterm Project

    Filename: combinedSchema.xsd
    Author:   Danielle Hyland
    Date:     11/03/18

	Filename:          combinedSchema.xsd
	Supporting file:   combinedVocab.xml, Vocab2bSchema.xsd
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://example.com/laptops"
           targetNamespace="http://example.com/laptops"
           xmlns:des="http://example.com/desktops">
<!--Imports the Vocab2bSchema.xsd file and the desktop schema to the document-->
<xs:import
		namespace="http://example.com/desktops"
		schemaLocation="Vocab2bSchema.xsd" />

<!--Complex root element laptops that contains one or more of the child element computer-->
<xs:element name="laptops">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="computer" minOccurs="1" maxOccurs="unbounded" />
      <!--This is a reference to the des:desktop object from the Vocab2b Schema -->
      <xs:element ref="des:desktops" />
    </xs:sequence>
  </xs:complexType>
</xs:element>

<!--Complex element computer that only contains the nested child model-->
<xs:element name="computer">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="model" />
    </xs:sequence>
  </xs:complexType>
</xs:element>

<!--Complex element model that only contains the nested children elements desc, specs, and price, and also has the attribute modelNumber which is required-->
<xs:element name="model">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="desc" /> 
      <xs:element ref="specs" />
      <xs:element ref="price" />
    </xs:sequence>
    <xs:attribute ref="modelNumber" use="required" />
  </xs:complexType>
</xs:element>

<!--The attribute modelNumber contains string data-->
<xs:attribute name="modelNumber" type="xs:string" />
<!--The simple element desc contains string data-->
<xs:element name="desc" type="xs:string" />

<!--The complex element price, which contains string data, as well as an attribute currency, which is required-->
<xs:element name="price">
  <xs:complexType>
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute ref="currency" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:element>

<!--The attribute currency which contains string data-->
<xs:attribute name="currency" type="xs:string" />

<!--Complex element spec that only contains the nested children elements processor, storageSpace, ram, graphicsCard (which may occur more then once), display and touchBar-->
<xs:element name="specs">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="processor" /> 
      <xs:element ref="storageSpace" />
      <xs:element ref="ram" />       
      <xs:element ref="graphicsCard" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element ref="display" />
      <xs:element ref="touchBar" />
    </xs:sequence>
  </xs:complexType>
</xs:element>

<!--Simple Element processor that contains string data-->
<xs:element name="processor" type="xs:string" /> 
<!--Simple Element storageSpace that contains string data-->
<xs:element name="storageSpace" type="xs:string" />
<!--Simple Element ram that contains string data-->
<xs:element name="ram" type="xs:string" />      
<!--Simple Element graphicsCard that contains string data-->
<xs:element name="graphicsCard" type="xs:string" />
<!--Simple Element display that contains string data-->
<xs:element name="display" type="xs:string" />

<!--Complex element type touchBar that only contains string data as well as the attribute included-->
<xs:element name="touchBar">
  <xs:complexType>
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute ref="included" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:element>

<!-- Attribute included that is a custom data type that is based string data type but is restricted to only Y or N -->
<xs:attribute name="included">
    <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="Y" />
          <xs:enumeration value="N" />
        </xs:restriction>
    </xs:simpleType>
</xs:attribute>

</xs:schema>

=== DanielleAlloy/XML-capstone-project/combinedVocab.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!--
    Macintosh Laptop and Desktop Computers Comparison
	BCS 303 - Final Project

    Filename: combinedVocab.xml
    Author:   Danielle Hyland
    Date:     12/03/18

	Filename:          combinedVocab.xml
	Supporting file:   combinedSchema.xml, Vocab2bSchema.xsd, combined.xsl
-->
<!--Links the XSL style sheet to the XML file-->
<?xml-stylesheet type="text/xsl" href="combined.xsl" ?>

<!--This is a compound document containing both Vocabulary1.xml & Vocabulary2.xml-->

<!--List of different Macintosh Laptop computers-->
<!--Turns into an instance document and declares that the document has a namespace-->
<!--Declares the namespace and schema location-->
<lap:laptops xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:lap="http://example.com/laptops"
             xsi:schemaLocation="http://example.com/laptops combinedSchema.xsd">

    <!--First instance of computer element-->
	<lap:computer>
	  <lap:model lap:modelNumber="A1708">
		<lap:desc>13" MacBook Pro; Mid 2017</lap:desc>
		<lap:specs>
			<lap:processor>2.3GHz dual-core Intel Core i5</lap:processor>
			<lap:storageSpace>128 GB</lap:storageSpace>
			<lap:ram>8GB</lap:ram>
			<lap:graphicsCard>Intel Iris Plus Graphics 640</lap:graphicsCard>
			<lap:display>Retina display</lap:display>
			<lap:touchBar lap:included="N">no</lap:touchBar>
		</lap:specs>
		<lap:price lap:currency="USD">1299</lap:price>
	  </lap:model>
	</lap:computer>
    <!--Second instance of computer element-->
    <lap:computer>
	  <lap:model lap:modelNumber="A1708">
		<lap:desc>13" MacBook Pro; Mid 2017</lap:desc>
		<lap:specs>
			<lap:processor>2.3GHz dual-core Intel Core i5</lap:processor>
			<lap:storageSpace>256 GB SSD</lap:storageSpace>
			<lap:ram>8GB</lap:ram>
			<!--one of more instances of graphicsCard-->
			<lap:graphicsCard>Intel Iris Plus Graphics 640</lap:graphicsCard>
			<lap:display>Retina display</lap:display>
			<lap:touchBar lap:included="N">no</lap:touchBar>
		</lap:specs>
		<lap:price lap:currency="USD">1499</lap:price>
	  </lap:model>
	</lap:computer>        
    <!--Third instance of computer element-->
    <lap:computer>
	  <lap:model lap:modelNumber="A1989">
		<lap:desc>13" MacBook Pro; Mid 2018</lap:desc>
		<lap:specs>
			<lap:processor>2.3GHz quad-core Intel Core i5</lap:processor>
			<lap:storageSpace>256GB SSD</lap:storageSpace>
			<lap:ram>8GB</lap:ram>
			<!--one of more instances of graphicsCard-->
			<lap:graphicsCard>Intel Iris Plus Graphics 655</lap:graphicsCard>
			<lap:display>Retina display</lap:display>
			<lap:touchBar lap:included="Y">yes</lap:touchBar>
		</lap:specs>
		<lap:price lap:currency="USD">1799</lap:price>
	  </lap:model>
	</lap:computer>        
    <!--Fourth instance of computer element-->
    <lap:computer>
	  <lap:model lap:modelNumber="A1989">
		<lap:desc>13" MacBook Pro; Mid 2018</lap:desc>
		<lap:specs>
			<lap:processor>2.3GHz quad-core Intel Core i5</lap:processor>
			<lap:storageSpace>512 GB SSD</lap:storageSpace>
			<lap:ram>8GB</lap:ram>
			<!--one of more instances of graphicsCard-->
			<lap:graphicsCard>Intel Iris Plus Graphics 655</lap:graphicsCard>
			<lap:display>Retina display</lap:display>
			<lap:touchBar lap:included="Y">yes</lap:touchBar>
		</lap:specs>
		<lap:price lap:currency="USD">1999</lap:price>
	  </lap:model>
	</lap:computer>
    <!--Fifth instance of computer element-->
    <lap:computer>
	  <lap:model lap:modelNumber="A1990">
		<lap:desc>15" MacBook Pro; Mid 2018</lap:desc>
		<lap:specs>
			<lap:processor>2.2GHz 6-core Intel Core i7</lap:processor>
			<lap:storageSpace>256 GB SSD</lap:storageSpace>
			<lap:ram>16GB</lap:ram>
			<!--one of more instances of graphicsCard-->
			<lap:graphicsCard>Radeon Pro 555X with 4GB of GDDR5 memory</lap:graphicsCard>
            <lap:graphicsCard>Intel UHD Graphics 630</lap:graphicsCard>
			<lap:display>Retina display</lap:display>
			<lap:touchBar lap:included="Y">yes</lap:touchBar>
		</lap:specs>
		<lap:price lap:currency="USD">2399</lap:price>
	  </lap:model>
    </lap:computer>
    <!--Sixth instance of computer element-->
    <lap:computer>
	  <lap:model lap:modelNumber="A1990">
		<lap:desc>15" MacBook Pro; Mid 2018</lap:desc>
		<lap:specs>
			<lap:processor>2.6GHz 6-core Intel Core i7</lap:processor>
			<lap:storageSpace>512 GB SSD</lap:storageSpace>
			<lap:ram>16GB</lap:ram>
			<!--one of more instances of graphicsCard-->
			<lap:graphicsCard>Radeon Pro 560X with 4GB of GDDR5 memory</lap:graphicsCard>
            <lap:graphicsCard>Intel UHD Graphics 630</lap:graphicsCard>
			<lap:display>Retina display</lap:display>
			<lap:touchBar lap:included="Y">yes</lap:touchBar>
		</lap:specs>
		<lap:price lap:currency="USD">2799</lap:price>
	  </lap:model>
    </lap:computer>

<!--List of different Macintosh Desktop computers-->
<des:desktops xmlns:des="http://example.com/desktops"
          	  xsi:schemaLocation="http://example.com/desktop Vocab2bSchema.xsd">
    <!--First instance of desktop computer element-->
	<des:computer>
	  <des:model des:modelNumber="A1418">
		<des:desc>21.5" iMac; Mid 2017</des:desc>
		<des:specs>
			<des:processor>2.3GHz dual-core Intel Core i5</des:processor>
			<des:storageSpace>1TB hard drive</des:storageSpace>
			<des:ram>8GB</des:ram>
            <!--one of more instances of graphicsCard-->
			<des:graphicsCard>Intel Iris Plus Graphics 640</des:graphicsCard>
			<des:display>LED-backlit display</des:display>
            <!--one of more instances of ports-->
            <des:ports>Two Thunderbolt 3 ports</des:ports>
            <des:ports>Four USB 3 ports</des:ports>
		</des:specs>
		<des:price des:currency="USD">1099</des:price>
	  </des:model>
	</des:computer>
    <!--Second instance of desktop computer element-->
    <des:computer>
	  <des:model des:modelNumber="A1418">
		<des:desc>21.5" iMac; Mid 2017</des:desc>
		<des:specs>
			<des:processor>3.0GHz quad‑core Intel Core i5</des:processor>
			<des:storageSpace>1TB hard drive</des:storageSpace>
			<des:ram>8GB</des:ram>
            <!--one of more instances of graphicsCard-->
			<des:graphicsCard>Radeon Pro 555 with 2GB of VRAM</des:graphicsCard>
			<des:display>Retina 4K display</des:display>
            <!--one of more instances of ports-->
            <des:ports>Two Thunderbolt 3 ports</des:ports>
            <des:ports>Four USB 3 ports</des:ports>
		</des:specs>
		<des:price des:currency="USD">1299</des:price>
	  </des:model>
	</des:computer>        
    <!--Third instance of desktop computer element-->
    <des:computer>
	  <des:model des:modelNumber="A1418">
		<des:desc>21.5" iMac; Mid 2017</des:desc>
		<des:specs>
			<des:processor>3.4GHz quad‑core Intel Core i5</des:processor>
			<des:storageSpace>1TB Fusion drive</des:storageSpace>
			<des:ram>8GB</des:ram>
            <!--one of more instances of graphicsCard-->
			<des:graphicsCard>Radeon Pro 560 with 4GB of VRAM</des:graphicsCard>
			<des:display>Retina 4K display</des:display>
            <!--one of more instances of ports-->
            <des:ports>Two Thunderbolt 3 ports</des:ports>
            <des:ports>Four USB 3 ports</des:ports>
		</des:specs>
		<des:price des:currency="USD">1499</des:price>
	  </des:model>
	</des:computer>        
    <!--Fourth instance of desktop computer element-->
    <des:computer>
	  <des:model des:modelNumber="A1419">
		<des:desc>27" iMac; Mid 2017</des:desc>
		<des:specs>
			<des:processor>3.4GHz quad‑core Intel Core i5</des:processor>
			<des:storageSpace>1TB Fusion drive</des:storageSpace>
			<des:ram>8GB</des:ram>
            <!--one of more instances of graphicsCard-->
			<des:graphicsCard>Radeon Pro 570 with 4GB of VRAM</des:graphicsCard>
			<des:display>Retina 5K display</des:display>
            <!--one of more instances of ports-->
            <des:ports>Two Thunderbolt 3 ports</des:ports>
            <des:ports>Four USB 3 ports</des:ports>
		</des:specs>
		<des:price des:currency="USD">1799</des:price>
	  </des:model>
	</des:computer>
    <!--Fifth instance of desktop computer element-->
    <des:computer>
	  <des:model des:modelNumber="A1419">
		<des:desc>27" iMac; Mid 2017</des:desc>
		<des:specs>
			<des:processor>3.5GHz quad‑core Intel Core i5</des:processor>
			<des:storageSpace>1TB Fusion drive</des:storageSpace>
			<des:ram>8GB</des:ram>
            <!--one of more instances of graphicsCard-->
			<des:graphicsCard>Radeon Pro 575 with 4GB of VRAM</des:graphicsCard>
			<des:display>Retina 5K display</des:display>
            <!--one of more instances of ports-->
            <des:ports>Two Thunderbolt 3 ports</des:ports>
            <des:ports>Four USB 3 ports</des:ports>
		</des:specs>
		<des:price des:currency="USD">1999</des:price>
	  </des:model>
	</des:computer>
    <!--Sixth instance of desktop computer element-->
    <des:computer>
	  <des:model des:modelNumber="A1419">
		<des:desc>27" iMac; Mid 2017</des:desc>
		<des:specs>
			<des:processor>3.8GHz quad‑core Intel Core i5 </des:processor>
			<des:storageSpace>2TB Fusion drive</des:storageSpace>
			<des:ram>8GB</des:ram>
            <!--one of more instances of graphicsCard-->
			<des:graphicsCard>Radeon Pro 580 with 8GB of VRAM</des:graphicsCard>
			<des:display>Retina 5K display</des:display>
            <!--one of more instances of ports-->
            <des:ports>Two Thunderbolt 3 ports</des:ports>
            <des:ports>Four USB 3 ports</des:ports>
		</des:specs>
		<des:price des:currency="USD">2299</des:price>
	  </des:model>
	</des:computer>
</des:desktops>
</lap:laptops>
