=== DanielleAlloy/XML-capstone-project/Vocab2Schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
    Macintosh Desktop Computers Comparison
	  BCS 303 - Midterm Project

    Filename: Vocab2Schema.xsd
    Author:   Danielle Hyland
    Date:     11/03/18

	Filename:          Vocab2Schema.xsd
	Supporting file:   Vocabulary2.xml
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">	

<!--Complex root element desktops that contains one or more of the child element computer-->
<xs:element name="desktops">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="computer" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
</xs:element>

<!--Complex element computer that only contains the nested child model-->
<xs:element name="computer">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="model" />
    </xs:sequence>
  </xs:complexType>
</xs:element>

<!--Complex element model that only contains the nested children elements desc, specs, and price, and also has the attribute modelNumber which is required-->
<xs:element name="model">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="desc" /> 
      <xs:element ref="specs" />
      <xs:element ref="price" />
    </xs:sequence>
    <xs:attribute ref="modelNumber" use="required" />
  </xs:complexType>
</xs:element>

<!--The attribute modelNumber contains string data-->
<xs:attribute name="modelNumber" type="xs:string" />
<!--The simple element desc contains string data-->
<xs:element name="desc" type="xs:string" />

<!--The complex element price, which contains string data, as well as an attribute currency, which is required-->
<xs:element name="price">
  <xs:complexType>
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute ref="currency" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:element>

<!--The attribute currency which contains string data-->
<xs:attribute name="currency" type="xs:string" />

<!--Complex element spec that only contains the nested children elements processor, storageSpace, ram, graphicsCard (which may occur more then once), display and ports (which may occur more than once)-->
<xs:element name="specs">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="processor" /> 
      <xs:element ref="storageSpace" />
      <xs:element ref="ram" />       
      <xs:element ref="graphicsCard" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element ref="display" />
      <xs:element ref="ports" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<!--Simple Element processor that contains string data-->
<xs:element name="processor" type="xs:string" /> 
<!--Simple Element storageSpace that contains string data-->
<xs:element name="storageSpace" type="xs:string" />
<!--Simple Element ram that contains string data-->
<xs:element name="ram" type="xs:string" />      
<!--Simple Element graphicsCard that contains string data-->
<xs:element name="graphicsCard" type="xs:string" />
<!--Simple Element display that contains string data-->
<xs:element name="display" type="xs:string" />
<!--Complex element type touchBar that only contains string data as well as the attribute included-->
<xs:element name="ports" type="xs:string" />

</xs:schema>

=== DanielleAlloy/XML-capstone-project/Vocabulary2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!--
    Macintosh Desktop Computers Comparison
	BCS 303 - Final Project Project

    Filename: Vocabulary2.xml
    Author:   Danielle Hyland
    Date:     12/03/18

	Filename:          Vocabulary2.xml
	Supporting file:   Vocab2Schema.xsd, desktops.xsl
-->

<!--Links the XSL style sheet to the XML file-->
<?xml-stylesheet type="text/xsl" href="desktops.xsl" ?>

<!--List of different Macintosh Desktop computers-->
<!--Turns into an instance document and declare that there is no namespace-->
<desktops xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="Vocab2Schema.xsd">
    <!--First instance of computer element-->
	<computer>
	  <model modelNumber="A1418">
		<desc>21.5" iMac; Mid 2017</desc>
		<specs>
			<processor>2.3GHz dual-core Intel Core i5</processor>
			<storageSpace>1TB hard drive</storageSpace>
			<ram>8GB</ram>
            <!--one of more instances of graphicsCard-->
			<graphicsCard>Intel Iris Plus Graphics 640</graphicsCard>
			<display>LED-backlit display</display>
            <!--one of more instances of ports-->
            <ports>Two Thunderbolt 3 ports</ports>
            <ports>Four USB 3 ports</ports>
		</specs>
		<price currency="USD">1099</price>
	  </model>
	</computer>
    <!--Second instance of computer element-->
    <computer>
	  <model modelNumber="A1418">
		<desc>21.5" iMac; Mid 2017</desc>
		<specs>
			<processor>3.0GHz quad‑core Intel Core i5</processor>
			<storageSpace>1TB hard drive</storageSpace>
			<ram>8GB</ram>
            <!--one of more instances of graphicsCard-->
			<graphicsCard>Radeon Pro 555 with 2GB of VRAM</graphicsCard>
			<display>Retina 4K display</display>
            <!--one of more instances of ports-->
            <ports>Two Thunderbolt 3 ports</ports>
            <ports>Four USB 3 ports</ports>
		</specs>
		<price currency="USD">1299</price>
	  </model>
	</computer>        
    <!--Third instance of computer element-->
    <computer>
	  <model modelNumber="A1418">
		<desc>21.5" iMac; Mid 2017</desc>
		<specs>
			<processor>3.4GHz quad‑core Intel Core i5</processor>
			<storageSpace>1TB Fusion drive</storageSpace>
			<ram>8GB</ram>
            <!--one of more instances of graphicsCard-->
			<graphicsCard>Radeon Pro 560 with 4GB of VRAM</graphicsCard>
			<display>Retina 4K display</display>
            <!--one of more instances of ports-->
            <ports>Two Thunderbolt 3 ports</ports>
            <ports>Four USB 3 ports</ports>
		</specs>
		<price currency="USD">1499</price>
	  </model>
	</computer>        
    <!--Fourth instance of computer element-->
    <computer>
	  <model modelNumber="A1419">
		<desc>27" iMac; Mid 2017</desc>
		<specs>
			<processor>3.4GHz quad‑core Intel Core i5</processor>
			<storageSpace>1TB Fusion drive</storageSpace>
			<ram>8GB</ram>
            <!--one of more instances of graphicsCard-->
			<graphicsCard>Radeon Pro 570 with 4GB of VRAM</graphicsCard>
			<display>Retina 5K display</display>
            <!--one of more instances of ports-->
            <ports>Two Thunderbolt 3 ports</ports>
            <ports>Four USB 3 ports</ports>
		</specs>
		<price currency="USD">1799</price>
	  </model>
	</computer>
    <!--Fifth instance of computer element-->
    <computer>
	  <model modelNumber="A1419">
		<desc>27" iMac; Mid 2017</desc>
		<specs>
			<processor>3.5GHz quad‑core Intel Core i5</processor>
			<storageSpace>1TB Fusion drive</storageSpace>
			<ram>8GB</ram>
            <!--one of more instances of graphicsCard-->
			<graphicsCard>Radeon Pro 575 with 4GB of VRAM</graphicsCard>
			<display>Retina 5K display</display>
            <!--one of more instances of ports-->
            <ports>Two Thunderbolt 3 ports</ports>
            <ports>Four USB 3 ports</ports>
		</specs>
		<price currency="USD">1999</price>
	  </model>
	</computer>
    <!--Sixth instance of computer element-->
    <computer>
	  <model modelNumber="A1419">
		<desc>27" iMac; Mid 2017</desc>
		<specs>
			<processor>3.8GHz quad‑core Intel Core i5 </processor>
			<storageSpace>2TB Fusion drive</storageSpace>
			<ram>8GB</ram>
            <!--one of more instances of graphicsCard-->
			<graphicsCard>Radeon Pro 580 with 8GB of VRAM</graphicsCard>
			<display>Retina 5K display</display>
            <!--one of more instances of ports-->
            <ports>Two Thunderbolt 3 ports</ports>
            <ports>Four USB 3 ports</ports>
		</specs>
		<price currency="USD">2299</price>
	  </model>
	</computer>
</desktops>
